---
  - name: BEGINING NTP CONFIGURATION FOR {{ host }}  
    hosts: "{{host}}"
    gather_facts: no
    connection: local

    tasks:
      - name: EXTRACTING CURRENT NTP CONFIGURATION FOR {{ host }}   
        no_log: True
        comware_command:
           command:
               - display current-configuration | i ntp
           type: display
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_1
      - debug:
          var=print_output_1
      - set_fact:
          print_output_2: "{{ print_output_1.response.split(' ') }}"
        when: '"ntp" in print_output_1.response'  
      - debug:
          var=print_output_2
      - set_fact:
          print_output_3: "{{ print_output_2[12] | regex_replace('\\r\\n','') }}"
        when: '"ntp" in print_output_1.response'
      - debug:
          var=print_output_3
      - set_fact:
          print_output_4: "{{ print_output_2[16] | regex_replace('\\r\\n','') }}"
        when: '"ntp" in print_output_1.response'
      - debug:
          var=print_output_4
   #   - set_fact:
   #       print_output_5: "{{ print_output_2[9] | regex_replace('\\r\\n','') }}"
   #   - debug:
   #       var=print_output_5
          
      - name: BEGINING NTP CONFIGURATION  
        no_log: True
        comware_command:
           command:
                - undo ntp-service enable
                - undo ntp-service source 
                - undo ntp-service unicast-server {{ print_output_3 }}
                - undo ntp-service unicast-server {{ print_output_4 }}
                - ntp-service enable
                - ntp-service source {{ ntpvlan }}
                - ntp-service unicast-server {{ ntp1 }} priority
                - ntp-service unicast-server {{ ntp2 }}
           type: config
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_5
      - pause: seconds=60
      - name: VERIFYING RESULTS AFTER APPLYING NTP CONFIGURATION    
        no_log: True
        comware_command:
           command:
               - display ntp status
           type: display
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_6

      - debug:
          msg: "NTP CONFIGURATION APPLIED SUCCESSFULLY. CLOCK STATUS IS SYNCRONIZED"
        when: '"synchronized" in print_output_6.response'
      - debug:
          msg: "NTP CONFIGURATION APPLIED UNSUCCESSFULLY. CLOCK STATUS IS UNSYNCRONIZED. PLEASE REFER TO ENGINEERING"
        when: '"unsynchronized" in print_output_6.response'
