---
  - name: BEGINING NTP CONFIGURATION FOR {{ host }}  
    hosts: "{{host}}"
    gather_facts: no
    connection: local

    tasks:
      - name: EXTRACTING CURRENT NTP CONFIGURATION FOR {{ host }}   
        no_log: True
        comware_command:
           command:
               - display current-configuration | i ntp
           type: display
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_1

      - set_fact:
          print_output_2: "{{ print_output_1.response.split(' ') }}"
      - debug:
          var=print_output_2
      - set_fact:
          print_output_3: "{{ print_output_2[8] | regex_replace('\\r\\n','') }}"
      - debug:
          var=print_output_3
