---
  - name: BEGINING NTP CONFIGURATION FOR {{ host }}  
    hosts: "{{host}}"
    gather_facts: no
    connection: local

    tasks:
      - name: EXTRACTING CURRENT NTP CONFIGURATION FOR {{ host }}   
        no_log: True
        comware_command:
           command:
               - display current-configuration | i unicast-server
           type: display
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_1
 #     - debug:
 #         var=print_output_1.response
      - set_fact:
          print_output_2: "{{ print_output_1.response.split(' ') }}"
        when: '"unicast-server" in print_output_1.response'  
  #    - debug:
  #        var=print_output_2
      - set_fact:
          print_output_3: "{{ print_output_2[7] | regex_replace('\\r\\n','') }}"
        when: '"unicast-server" in print_output_1.response' 
   #   - debug:
   #       var=print_output_3
      - set_fact:
          print_output_4: "{{ print_output_2[11] | regex_replace('\\r\\n','') }}"
        when: '"unicast-server" in print_output_1.response' 
   #   - debug:
   #       var=print_output_4
#      - set_fact:
#          print_output_5: "{{ print_output_2[14] | regex_replace('\\r\\n','') }}"
#        when: '"unicast-server" in print_output_1.response' 
#      - debug:
#          var=print_output_5
   
      - name: REMOVING PREVIOUS NTP CONFIGURATIONS AND CONFIGURING NEW SERVERS   
        no_log: True
        comware_command:
           command:
                - undo ntp-service enable
                - undo ntp-service source 
                - undo ntp-service unicast-server {{ print_output_2 }}
                - undo ntp-service unicast-server {{ print_output_3 }}
                - ntp-service enable
                - ntp-service source {{ ntpvlan }}
                - ntp-service unicast-server {{ ntp1 }} priority
                - ntp-service unicast-server {{ ntp2 }}
           type: config
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_6
        when: '"unicast-server" in print_output_1.response'
      - debug:
          var=print_output_6
      
      - name: BEGINING NTP CONFIGURATION   
        no_log: True
        comware_command:
           command:
                - undo ntp-service enable
                - undo ntp-service source 
                - ntp-service enable
                - ntp-service source {{ ntpvlan }}
                - ntp-service unicast-server {{ ntp1 }} priority
                - ntp-service unicast-server {{ ntp2 }}
           type: config
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_6
        when: '"unicast-server" not in print_output_1.response'
      - debug:
          var=print_output_6
      - pause: seconds=60
      
      - name: VERIFYING RESULTS AFTER APPLYING NTP CONFIGURATION    
        no_log: True
        comware_command:
           command:
               - display ntp status
           type: display
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_6

      - debug:
          msg: "NTP CONFIGURATION APPLIED SUCCESSFULLY. CLOCK STATUS IS SYNCRONIZED"
        when: '"synchronized" in print_output_6.response'
      - debug:
          msg: "NTP CONFIGURATION APPLIED UNSUCCESSFULLY. CLOCK STATUS IS UNSYNCRONIZED. PLEASE REFER TO ENGINEERING"
        when: '"unsynchronized" in print_output_6.response'

