---
  - name: BEGINING NTP CONFIGURATION FOR {{ host }}  
    hosts: "{{host}}"
    gather_facts: no
    connection: local

    tasks:
      - name: EXTRACTING CURRENT NTP CONFIGURATION FOR {{ host }}   
        no_log: True
        comware_command:
           command:
               - display current-configuration | i ntp
           type: display
           username: "{{ username }}"
           password: "{{ password }}"
           hostname: "{{ inventory_hostname }}"
        register: print_output_1

      - set_fact:
          print_output_2: "{{ print_output_1.response.split(' ') }}"
      - debug:
          var=print_output_2
      - set_fact:
          print_output_3: "{{ print_output_2[12] | regex_replace('\\r\\n','') }}"
      - debug:
          var=print_output_3
      - set_fact:
          print_output_4: "{{ print_output_2[16] | regex_replace('\\r\\n','') }}"
      - debug:
          var=print_output_4
      - set_fact:
          print_output_5: "{{ print_output_2[9] | regex_replace('\\r\\n','') }}"
      - debug:
          var=print_output_5
          
#      - name: BEGINING NTP CONFIGURATION  
#        no_log: True
#        comware_command:
#           command:
#                - undo ntp-service enable
#                - ntp-service source {{ vlan-interface }}
#                - ntp-service unicast-server 138.35.151.48 priority
#               - ntp-service unicast-server 138.35.151.112
#           type: config
#           username: "{{ username }}"
#           password: "{{ password }}"
#           hostname: "{{ inventory_hostname }}"
#        when: '"DOWN" in print_output_1.response'
#        register: print_output_5
